import React from "react";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/Footer";
import AboutUs from "./components/homepage/parts/AboutUs";
import Founder from "./components/homepage/parts/Founder";
import Achievements from "./components/homepage/parts/Achievements";
import Head from "next/head";

const signup = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <AboutUs />
      <Founder />
      <Achievements />
      <Footer />
    </>
  );
};

export default signup;
