import React from "react";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/Footer";
import Contactus from "./components/homepage/parts/Contactus";
import ContactForm from "./components/homepage/parts/ContactForm";
import Head from "next/head";

const signup = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Navbar />
      <Contactus />
      <ContactForm />
      <Footer />
    </>
  );
};

export default signup;
