import React from "react";
import Head from "next/head";
import AppliedInternships from "../components/User/AppliedInternships";

const appliedInternships = () => {
  return (
    <>
      <Head>
        <title>AppliedInternships</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppliedInternships />
    </>
  );
};

export default appliedInternships;
