import React from "react";
import Head from "next/head";
import SavedInternships from "../components/User/SavedInternships";

const savedInternships = () => {
  return (
    <>
      <Head>
        <title>savedInternships</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SavedInternships />
    </>
  );
};

export default savedInternships;
